In [1]:
import numpy as np # needed for array
import pandas as pd # needed for reading CSV
import matplotlib.pyplot as plt # for common graph plotting

In [2]:
data_train = pd.read_csv('optdigits.tra.csv')
data_test = pd.read_csv('optdigits.tes.csv')

print(data_train.shape)
print(data_test.shape)

(3823, 65)
(1797, 65)


In [3]:
train_X = data_train[['x11','x12','x13','x14','x15','x16','x17','x18','x21','x22','x23','x24','x25','x26','x27','x28','x31','x32','x33','x34','x35','x36','x37','x38','x41','x42','x43','x44','x45','x46','x47','x48','x51','x52','x53','x54','x55','x56','x57','x58','x61','x62','x63','x64','x65','x66','x67','x68','x71','x72','x73','x74','x75','x76','x77','x78','x81','x82','x83','x84','x85','x86','x87','x88']] # taking the training data features
train_y = data_train.digit # output of the training data

test_X = data_test[['x11','x12','x13','x14','x15','x16','x17','x18','x21','x22','x23','x24','x25','x26','x27','x28','x31','x32','x33','x34','x35','x36','x37','x38','x41','x42','x43','x44','x45','x46','x47','x48','x51','x52','x53','x54','x55','x56','x57','x58','x61','x62','x63','x64','x65','x66','x67','x68','x71','x72','x73','x74','x75','x76','x77','x78','x81','x82','x83','x84','x85','x86','x87','x88']] # taking test data feature
test_y = data_test.digit # output value of the test data

In [4]:
train_X.head()

x11  x12  x13  x14  x15  x16  x17  x18  x21  x22 ...   x77  x78  x81  x82  \
0    0    1    6   15   12    1    0    0    0    7 ...     0    0    0    0   
1    0    0   10   16    6    0    0    0    0    7 ...     3    0    0    0   
2    0    0    8   15   16   13    0    0    0    1 ...     0    0    0    0   
3    0    0    0    3   11   16    0    0    0    0 ...     0    0    0    0   
4    0    0    5   14    4    0    0    0    0    0 ...    12    0    0    0   

   x83  x84  x85  x86  x87  x88  
0    6   14    7    1    0    0  
1   10   16   15    3    0    0  
2    9   14    0    0    0    0  
3    0    1   15    2    0    0  
4    4   12   14    7    0    0  

[5 rows x 64 columns]

In [5]:
test_X.head()

x11  x12  x13  x14  x15  x16  x17  x18  x21  x22 ...   x77  x78  x81  x82  \
0    0    0    5   13    9    1    0    0    0    0 ...     0    0    0    0   
1    0    0    0   12   13    5    0    0    0    0 ...     0    0    0    0   
2    0    0    0    4   15   12    0    0    0    0 ...     5    0    0    0   
3    0    0    7   15   13    1    0    0    0    8 ...     9    0    0    0   
4    0    0    0    1   11    0    0    0    0    0 ...     0    0    0    0   

   x83  x84  x85  x86  x87  x88  
0    6   13   10    0    0    0  
1    0   11   16   10    0    0  
2    0    3   11   16    9    0  
3    7   13   13    9    0    0  
4    0    2   16    4    0    0  

[5 rows x 64 columns]

In [6]:
train_y.head()

0    0
1    0
2    7
3    4
4    6
Name: digit, dtype: int64

In [7]:
#Now I'll try calculating the accuracy for K-Nearest Neighbors and replicate the results as given
#question 3) K-Nearest Neighbors

#! pip install -U scikit-learn

In [8]:
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split # to split the dataset for training and testing 
from sklearn.neighbors import KNeighborsClassifier # KNN classifier
from sklearn import metrics # for checking the model accuracy

In [9]:
model = KNeighborsClassifier(n_neighbors=1) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9799666110183639


In [10]:
model = KNeighborsClassifier(n_neighbors=2) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9738452977184195


In [11]:
model = KNeighborsClassifier(n_neighbors=3) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9782971619365609


In [12]:
model = KNeighborsClassifier(n_neighbors=4) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9766277128547579


In [13]:
model = KNeighborsClassifier(n_neighbors=5) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9788536449638287


In [14]:
model = KNeighborsClassifier(n_neighbors=6) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9777406789092933


In [15]:
model = KNeighborsClassifier(n_neighbors=7) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9766277128547579


In [16]:
model = KNeighborsClassifier(n_neighbors=8) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9766277128547579


In [17]:
model = KNeighborsClassifier(n_neighbors=9) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9771841958820257


In [18]:
model = KNeighborsClassifier(n_neighbors=10) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9755147468002225


In [19]:
model = KNeighborsClassifier(n_neighbors=11) # this examines 3 neighbors for putting the data into class
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the K-Nearest Neighbors is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the K-Nearest Neighbors is:  0.9794101279910963


In [20]:
#non-instance based classsifiers implementation
from sklearn import svm # for suport vector machine algorithm

In [21]:
model = svm.SVC() # select the svm algorithm
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the SVM is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

/Users/megs/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


The accuracy of the SVM is:  0.562047857540345


In [22]:
from sklearn.linear_model import LogisticRegression # for Logistic Regression Algorithm

In [23]:
model = LogisticRegression() #select the logistic regression algorithm
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the LogisticRegression is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

/Users/megs/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/megs/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


The accuracy of the LogisticRegression is:  0.9471341124095715


In [24]:
from sklearn.tree import DecisionTreeClassifier # for using DTA
model = DecisionTreeClassifier() #select the Decision Tree algorithm
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the Decision Tree is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the Decision Tree is:  0.8542014468558708


In [25]:
from sklearn.naive_bayes import GaussianNB #naivebayes

In [26]:
model = GaussianNB() #select NaiveBayes algorithm
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the NaiveBayes is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the NaiveBayes is:  0.7863105175292153


In [27]:
from sklearn.ensemble import RandomForestClassifier #RandomForest

In [28]:
model = RandomForestClassifier() #select the RandomForest algorithm
# we train the algorithm with training data and training output
model.fit(train_X, train_y)
# we pass the testing data to the stored algorithm to predict the outcome
prediction = model.predict(test_X)
print('The accuracy of the Random Forest is: ', metrics.accuracy_score(prediction, test_y)) # we check the accuracy of the algorithm
#we pass the predicted output by the model and the actual output

The accuracy of the Random Forest is:  0.9471341124095715


/Users/megs/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [29]:
# QUESTION 4)checking the precision for KNN (Instance based classifier)
import time
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

#neigh = KNeighborsClassifier(n_neighbors=3)
#neigh.fit(X, y) 
range_k = range(1, 9)
scores = []
best_k = 0

for k in range_k:
    
    start = time.time()
    print('k = ', str(k), 'begin')
    knn = KNeighborsClassifier(n_neighbors = k)
    knn.fit(train_X, train_y)
    
    y_pred = knn.predict(test_X)
    
    accuracy = accuracy_score(test_y, y_pred)
    scores.append(accuracy)
    end = time.time()
    
    print(classification_report(test_y, y_pred))
    print(confusion_matrix(test_y, y_pred))
    print('total time used is ', str(end - start), 'secs.')
    
#best_k = max(scores)
print('best k is ' )

k =  1 begin
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       178
           1       0.94      0.99      0.97       182
           2       1.00      0.99      0.99       177
           3       0.98      0.98      0.98       183
           4       0.98      0.98      0.98       181
           5       0.99      0.98      0.99       182
           6       1.00      1.00      1.00       181
           7       0.99      0.99      0.99       179
           8       0.97      0.94      0.96       174
           9       0.96      0.94      0.95       180

   micro avg       0.98      0.98      0.98      1797
   macro avg       0.98      0.98      0.98      1797
weighted avg       0.98      0.98      0.98      1797

[[178   0   0   0   0   0   0   0   0   0]
 [  0 181   0   0   0   0   0   0   1   0]
 [  0   2 175   0   0   0   0   0   0   0]
 [  0   0   0 179   0   0   0   2   0   2]
 [  0   2   0   0 178   0   0   0   1   0]
 [  0   0   0

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       178
           1       0.90      0.99      0.95       182
           2       1.00      0.97      0.99       177
           3       0.97      0.98      0.98       183
           4       0.99      0.99      0.99       181
           5       0.99      0.98      0.99       182
           6       0.99      1.00      1.00       181
           7       0.99      0.98      0.98       179
           8       0.98      0.91      0.94       174
           9       0.96      0.96      0.96       180

   micro avg       0.98      0.98      0.98      1797
   macro avg       0.98      0.98      0.98      1797
weighted avg       0.98      0.98      0.98      1797

[[178   0   0   0   0   0   0   0   0   0]
 [  0 181   0   0   0   0   1   0   0   0]
 [  0   4 172   0   0   0   0   1   0   0]
 [  0   1   0 179   0   1   0   1   1   0]
 [  0   2   0   0 179   0   0   0   0   0]
 [  0   0   0   0   1 179 

Explanation:
1)looking at the precision result above, I could see that KNN has performed well with a very high accuracy for the dataset. 
2)Based on that, though I would say that the instance based classifiers have performed better for this dataset when it comes to the higher accuracy,still there are various scenarios that needs to be considered:
3)Given this high classification accuracy, I feel that this exactly haven't solved the Digit Recognition problem.
4)Because it won't necessarily translate into the real-world viability.
5)After learning about the concept, I feel this is mainly due to the dataset itself, where each and every image might have been heavily pre-processed — including cropping, perfect thresholding, and centered.
6)And in the real world, I don't expect that the dataset would be so well pre-cleaned and pre-processed from before.
7)Eg. I can see certain digits such as 0, 2 with 100% precision. And even other digits are nearly accurate.
8)If I specifically talk about the instance based classifiers based on the performance observed (KNN Classifier), then in many cases it is well worth the effort and small loss in accuracy to use the k-NN algorithm.
9)All in all, the k-NN algorithm is more suited for low-dimensional feature spaces.

#Better accuracy for training set as compared to test set for Random Forest.